### ISSUE TITLE
[Feature Request] Add Support for Node-RED

### ISSUE THREAD

**Issue by Mannshoch** [Domi04151309/HomeApp#17]
**Describe the solution you'd like**

**Basic Support:**
- [x] Show the Dashboard `{Server}:1880/ui/`

**Enhanced Support**
- [x] Add a possibility to edit nodes `{Server}:1880/`
- [ ] Add possibility to send notification to HomeApp

<details>
The most easy part would be the viewing of the Dashboard. At moment HomeApp seems not able to show even that.
</details>

**Comment by Domi04151309** [comment]
I can add the basic support option but how does this differ from a normal webiste?

**Comment by Mannshoch** [comment]
Not sure, in Home app the Website open only a blank Page.

**Comment by Domi04151309** [comment]
The dashboard will be visible in the next release. The webView was not configured correctly for it to display.

**Comment by cweiske** [comment]
This is fixed with [release 1.7.3](https://github.com/Domi04151309/HomeApp/releases/tag/1.7.3).
Can this be closed now?
