### ISSUE TITLE
[Bug Report] Can't connect to diyHue

### ISSUE THREAD

**Issue by kompas1** [Domi04151309/HomeApp#18]
Okay so I set up a diyHue Bridge on my Pi and if I try to connect to it over the Hue Essentials App with the Hue API it's working just fine, but if I try to connect over the HomeApp and the Hue API I can't connect to the Bridge. I mean for sure I could also just use the website but I would really like to use the HomeApp since it is a good looking and also good working with other devices, like using and controlling the lamps on there own over the App

**Comment by Domi04151309** [comment]
Does it show any error messages?

**Comment by kompas1** [comment]
no, there are no error messages, just a blank screen after i tap on it

**Comment by Domi04151309** [comment]
Can you please send a screenshot?

**Comment by kompas1** [comment]
![grafik](https://user-images.githubusercontent.com/61203986/91962506-e8d6c080-ed0c-11ea-94b5-8a6e98db3504.png)

**Comment by kompas1** [comment]
@Domi04151309 I got it to work finally, I had to make some adjustments at the bridge itself
