### ISSUE TITLE
[Feature Request] Website Authentication

### ISSUE THREAD

**Issue by andersmmg** [Domi04151309/HomeApp#2]
My router requires HTTP authentication to access the system, but the app doesn't seem to support this. It shouldn't be too hard to implement and it would be really nice. This app seems very cool so far, setting up an ESP8266 went perfectly and the app looks nice.

**Comment by Domi04151309** [comment]
Thanks for your feedback! I don't really know what you mean by HTTP authentication. Do you mean [Basic access authentication](https://en.wikipedia.org/wiki/Basic_access_authentication)?

**Comment by andersmmg** [comment]
I believe so. When I connect to my router, it requires a username and
password from the browser before I can start using it. It doesn't have its
own login screen, it just uses HTTP auth

**Comment by andersmmg** [comment]
Thanks, by the way. It works perfectly!
