### ISSUE TITLE
[Bug Report] Hue - No scenes synced

### ISSUE THREAD

**Issue by dbkblk** [Domi04151309/HomeApp#20]
**Description**

I started the app, added my Hue bridge, tap the button to associate. It has correctly synced all the rooms and lights, but there are none of the scenes that are registered. I know the scenes are correctly registered in the bridge because I use the Hue app on Android and hueadm on Linux.

![Screenshot_20201127-135357_Home](https://user-images.githubusercontent.com/2344816/100451620-0327fc80-30b8-11eb-9bcc-66260b7abd04.png)

 - Android version: LineageOS 16.1, microg
 - Home App version: 1.7.2
 - Installation source: F-Droid

Thank you for the software, thus said :)

**Comment by Domi04151309** [comment]
Scenes are currently only available for rooms and zones. This is strange as I used the code from the official API.

**Comment by dbkblk** [comment]
Well, I tried both and none of them have scenes. Does it work for you?

Le 27 novembre 2020 13:58:04 GMT+01:00, Dominik <notifications@github.com> a écrit :

**Comment by Domi04151309** [comment]
![Screenshot_20201127-162557](https://user-images.githubusercontent.com/36272047/100464116-480a5e00-30cd-11eb-9754-ecc7d33b8942.jpg)
It should look like this.

**Comment by nhrjr** [comment]
I stumbled upon this bug, too, when creating 'Wake up routines' in the Philips Hue app, i.e. no scenes would be shown in the Home app.
Upon deletion of the wake up routines in the Philips App (or via hueadm), the scenes would show up again in the Home app, reproduciably.

**Comment by Domi04151309** [comment]
I was not able to reproduce this behavior. Can you provide steps on how you added your routines?

**Comment by Domi04151309** [comment]
I have this issue now as well

**Comment by doodhout** [comment]
I have the same problem but I have no wake-up routines configured.

Does the presence of "other routines" have the same effect as the original cause for this bug?
