### ISSUE TITLE
[Bug Report] A display bug

### ISSUE THREAD

**Issue by franklinbill** [Domi04151309/HomeApp#22]
**Description**

Dear developer! In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the lower part of the text in the red box is blocked, so you can only see “Your Dxxxx”. It may be an adaptation problem.
App version is 1.7.2, my mobile phone is Google nexus 6, screen resolution setting is 1920*1080, **_font size and display size_** are the **_largest_**! ! !, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!

<details>
  <summary><b>Screenshots</b></summary>
 
![bug-home_172](https://user-images.githubusercontent.com/18572115/103097147-4b97f300-4641-11eb-8271-3e58f8b8c835.png)

  _Add screenshots here to describe the problem._
</details>

<details>
  <summary><b>Logs</b></summary>

  _Add a detailed stack trace / crash log here if applicable_
</details>

**Additional information**

 - Android version: _System Settings > About > Android 8.0
 - Home App version: _Settings > About > 1.7.2
 - Installation source: F-Droid

**Comment by Domi04151309** [comment]
I have to admit that i did not test on very large font sizes. I will try fixing this
