### ISSUE TITLE
[Feature Request] Hue - Scene widgets

### ISSUE THREAD

**Issue by PanderMusubi** [Domi04151309/HomeApp#24]
Offer adding a widget for an available scene.

Of course, this issue has to solved first https://github.com/Domi04151309/HomeApp/issues/20

**Comment by Tobias-Lauerbach** [comment]
I woud linke to suggest that Widgets in General woud be a great Addition to your beautiful app.

**Comment by Domi04151309** [comment]
This is now available in the latest version.
