### ISSUE TITLE
[Feature Request] Use semantic versioning

### ISSUE THREAD

**Issue by cweiske** [Domi04151309/HomeApp#31]
Version 1.7.3 brings many new features, but the version number indicates that it's a bugfix release.

It would be nice if HomeApp would follow the "semantic versioning" rules: https://semver.org/

- Bugfix-only releases: Increase the 3rd number in the version: `x.y.z+1`
- Feature releases (even when they contain bugfixes): Increase the 2nd number, reset the 3rd to 0: `x.y+1.0`
- Breaking changes (removed features): Increase the major version, reset the others to 0: `x+1.0.0`.

**Comment by Domi04151309** [comment]
Sounds good. Next release will be 1.8.0.

**Comment by cweiske** [comment]
@Domi04151309 Version 1.8.1 should be 1.9.0 since HomeApp gets a new feature (realtime updates). 1.8.1 would be bugfixes only.
