### ISSUE TITLE
[Bug Report] App doesn't work through cellular network.

### ISSUE THREAD

**Issue by JohanSchmurge** [Domi04151309/HomeApp#45]
**Description**

After last update app don't work through cellular network. Through wifi work ok.

<details>
  <summary><b>Screenshots</b></summary>
![Screenshot_20211207-110802](https://user-images.githubusercontent.com/57623145/144991308-51dcd63b-77f6-4e65-80f1-050db459c70f.png)
![Screenshot_20211207-111301](https://user-images.githubusercontent.com/57623145/144991339-7ba92dd8-675c-4007-8d16-b46acb414de1.png)
</details>

**Additional information**

 - Android version: _System Settings > About > Android version 10
 - Home App version: _Settings > About > Version 1.7.3
 - Installation source: F-Drod

**Comment by Domi04151309** [comment]
That's intended behavior for security reasons.

**Comment by Domi04151309** [comment]
For enhanced security your smart home devices should not be accessible from the internet. Please reevaluate whether everybody on the internet should be able to access your smart home.

**Comment by JohanSchmurge** [comment]
Of course, but access from internet can be disabled on home router. And some devices can have access from internet, for example termometer.

**Comment by Domi04151309** [comment]
I will add a toggle in the settings with the next version.

**Comment by JohanSchmurge** [comment]
Thanks.

**Comment by JohanSchmurge** [comment]
And i have more one problem, don't work auto refresh in toast messages.
