### ISSUE TITLE
[Feature Request] Document simplehome mDNS discovery in wiki

### ISSUE THREAD

**Issue by cweiske** [Domi04151309/HomeApp#48]
**Describe the solution you'd like**

It would be nice if the (SimpleHomeApi)[https://github.com/Domi04151309/HomeApp/wiki/SimpleHome-API] wiki page would contain instructions about mDNS discovery, and how to configure avahi-daemon. (Mentioned in commit 6d492b81797c8bf838733f726f7696c2f3f049a9).

It'd be also nice there was an explanation how to setup UPnP announcements for own SimpleHomeApi services yourself.

----

The Shelly page should mention the devices known to work (and that others should work, too):
- Shelly 1 with temperature+humidity sensor
- Shelly Plug S
- Shelly Plus 1

The page should also mention that autodiscovery works with shelly devices.

**Comment by cweiske** [comment]
You could also give me access to the wiki and I'd do it myself.

**Comment by Domi04151309** [comment]
How do I give you access to the wiki?

**Comment by cweiske** [comment]
Done.

@Domi04151309 It'd be also nice there was an explanation how to setup UPnP announcements for own SimpleHomeApi services yourself.
I don't know how to do that.

**Comment by Domi04151309** [comment]
I have placed a link to the example that shows how it can be done with Arduinos.
