### ISSUE TITLE
[Feature Request] More/custom device icons

### ISSUE THREAD

**Issue by filip-769** [Domi04151309/HomeApp#62]
Add more device icons like security cameras, smart outlets... or maybe option to upload png/svg icon from storage.

**Comment by cweiske** [comment]
#58 brings some

**Comment by Domi04151309** [comment]
Using your own icons will not be implemented, because it requires too much effort for little added functionality. In addition to that, people will use bad icons that do not work well together or outright look bad. If you want to see any icons added, feel free to suggest them.
