### ISSUE TITLE
[Bug Report] Socket device icon looks bad

### ISSUE THREAD

**Issue by cweiske** [Domi04151309/HomeApp#66]
**Description**
The socket device icon in blue looks ugly on a white background.
The original one from #58 looked better in my eyes.

I presume you did that change because of white/dark themes.
Could there be an inverted one for the dark theme instead of using the blue one?

![Screenshot_20220107-185556_Home](https://user-images.githubusercontent.com/59036/148636452-7badd1b1-4e2f-43e2-9dd0-8f49a324bcc1.png)

**Comment by Domi04151309** [comment]
All the current icons use the colored icon style with adjusted colors to match the fluent icon style. I would like to use a colorful icon here as well. Feel free to suggest different fill colors for [the icon](https://github.com/Domi04151309/HomeApp/blob/master/app/src/main/res/drawable/ic_device_socket.xml#L3-L5). You can find the current icon on [Icons8](https://icons8.com/icon/zFlmUM9ch6eS/wall-socket).

**Comment by cweiske** [comment]
I like the icon that I selected originally most (#58), because the wall sockets actually look that way here. They are white and not blue, and the black outline makes sense.

**Comment by Domi04151309** [comment]
What do you think about the different colors in the latest commit. Your icon uses another icon style. I would like to use icons from the same style for consistency.

**Comment by cweiske** [comment]
We're talking about https://icons8.com/icon/7283/wall-socket and the icon styles "iOS" and "color", presumably with modified colors.

I don't see why we need a colored icon for a socket that is white in most houses.
Also, the "color" style of the wall socket icon is missing the nice rounded border that the iOS variant has.

But I'm tired discussing this. Feel free to close the issue without changes.
