### ISSUE TITLE
Wrong gradle version

### ISSUE THREAD

**Issue by cweiske** [Domi04151309/HomeApp#67]
I'm having this problem the 10th time now after resetting my git checkout --hard for #64 , so I post this as a bug.

When trying to build HomeApp with Android Studio 2020.3.1 I get an error:
```
Build file '/home/cweiske/dev/tools/HomeApp/app/build.gradle' line: 1

A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.android.internal.application'.
   > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
     You can try some of the following options:
       - changing the IDE settings.
       - changing the JAVA_HOME environment variable.
       - changing `org.gradle.java.home` in `gradle.properties`.
```

The solution is to open File > Settings → Build, Execution, Deployment → Build Tools → Gradle  and change "Gradle JDK".

This should be set automatically.

**Comment by Domi04151309** [comment]
Should be fixed now
